project_name: istio-checker
release:
  github:
    owner: myhops
    name: istio-checker
builds:
  - id: istio-checker
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/myhops/istio-checker/pkg/version.version=
archives:
  - id: istio-checker
    builds:
    - istio-checker
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
