apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: istio-checker
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/myhops/istio-checker/releases/download/v0.1.0/istio-checker_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./istio-checker"
      to: "."
    - from: LICENSE
      to: "."
    bin: "istio-checker"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/myhops/istio-checker/releases/download/v0.1.0/istio-checker_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./istio-checker"
      to: "."
    - from: LICENSE
      to: "."
    bin: "istio-checker"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/myhops/istio-checker/releases/download/v0.1.0/istio-checker_windows_amd64.zip
    sha256: ""
    files:
    - from: "/istio-checker.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "istio-checker.exe"
  shortDescription: A new plugin
  homepage: https://github.com/myhops/istio-checker
  caveats: |
    Usage:
      $ kubectl istio-checker

    For additional options:
      $ kubectl istio-checker --help
      or https://github.com/myhops/istio-checker/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
